from __future__ import annotations
import argparse,copy,hashlib,json,pathlib
from datetime import datetime,timezone,timedelta
TZ=timezone(timedelta(hours=3))
def load(p):return json.loads(pathlib.Path(p).read_text(encoding='utf-8'))
def digest(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--spec',required=True);ap.add_argument('--candidate-out',required=True);ap.add_argument('--canonical-out',required=True);ap.add_argument('--audit-out',required=True);a=ap.parse_args();s=load(a.spec);parent=load(s['parent_state']);ev=load(s['new_evidence']);req=s['required'];adm=ev.get('admitted_candidates',[]);k=[x for x in adm if x.get('source_word_after_scoring')=='KU-RO' and x.get('role')==req['KU_RO_role']]
 pre={'parent_v2_27':parent.get('version')=='v2.27' and parent.get('status')=='CURRENT_CANONICAL_RESEARCH_STATE','status_exact':ev.get('status')==s['required_status'],'admitted_8':ev.get('admitted_candidate_count')==req['admitted_candidate_count'] and len(adm)==8,'all_admitted_flags':all(x.get('POSITIONAL_TEMPLATE_CANDIDATE_ADMITTED') is True for x in adm),'ku_ro_one':len(k)==1,'ku_ro_n':len(k)==1 and k[0].get('heldout_occurrences')==req['KU_RO_heldout_occurrences'],'ku_ro_hits':len(k)==1 and k[0].get('heldout_matches')==req['KU_RO_heldout_matches'],'ku_ro_q':len(k)==1 and k[0].get('BH_q')==req['KU_RO_BH_q'],'no_probable':ev['epistemic_gate'].get('probable_function_established') is req['probable_function_established'],'translation_false':ev['epistemic_gate'].get('translation_established') is False,'anchor_false':ev['epistemic_gate'].get('new_anchor_established') is False,'decipherment_false':ev['epistemic_gate'].get('decipherment_established') is req['decipherment_established'],'labels_not_scoring':ev['leakage_firewall'].get('source_word_labels_used_for_selection_or_scoring') is False,'no_manual':ev['leakage_firewall'].get('manual_candidate_addition_or_removal') is False}
 if not all(pre.values()):raise SystemExit(json.dumps(pre,sort_keys=True))
 st=copy.deepcopy(parent);now=datetime.now(TZ).isoformat();st.update({'artifact_uuid':'JANUS-LINEAR-A-RESEARCH-STATE-2026-08-15-v2.28','timestamp':now,'version':'v2.28','title':'JANUS Linear A canonical state after cross-fitted positional-template candidate admission','status':'CURRENT_CANONICAL_RESEARCH_STATE'});st['canonicality']={'current_source_of_truth':True,'parent_state':s['parent_state'],'promotion_spec':a.spec,'promotion_prerequisites_pass':True,'history_is_not_deleted':True,'candidate_path':a.candidate_out,'canonicality_audit':a.audit_out,'canonicality_audit_status':'PENDING_UNTIL_AUDIT_EMITTED','promotion_rule_satisfied':True}
 frozen=[{'role':x['role'],'word_token':x['word_token'],'source_word_after_scoring':x['source_word_after_scoring'],'heldout_occurrences':x['heldout_occurrences'],'heldout_matches':x['heldout_matches'],'heldout_match_rate':x['heldout_match_rate'],'heldout_document_count':x['heldout_document_count'],'heldout_region_set':x['heldout_region_set'],'BH_q':x['BH_q']} for x in adm]
 lane=st.setdefault('R7_formula_role_lane',{});lane['R7_C0']={'path':s['new_evidence'],'status':ev['status'],'evidence_sha256':digest(s['new_evidence']),'candidate_family_frozen':True,'candidate_count':8,'frozen_candidates':frozen,'KU_RO_C0':{'role':k[0]['role'],'heldout_occurrences':k[0]['heldout_occurrences'],'heldout_matches':k[0]['heldout_matches'],'heldout_match_rate':k[0]['heldout_match_rate'],'heldout_document_count':k[0]['heldout_document_count'],'heldout_region_set':k[0]['heldout_region_set'],'p_value':k[0]['p_value'],'BH_q':k[0]['BH_q']}};lane['status']='R7_C0_EIGHT_CANDIDATES_FROZEN_VALIDATION_ONLY'
 road=[x for x in st.get('roadmap',[]) if x.get('id') not in {'R7_C_POSITIONAL_TEMPLATE_ROLES','R7_C1_COMPLETE_REGION_HOLDOUT','R7_C2_STRUCTURE_DESTROYING_NULL','R7_C3_PROBABLE_FUNCTION_ADMISSION'}];road.extend([{'id':'R7_C_POSITIONAL_TEMPLATE_ROLES','status':'DONE_ADMITTED_8_CANDIDATES_FROZEN'},{'id':'R7_C1_COMPLETE_REGION_HOLDOUT','status':'READY_FROZEN_8_ONLY'},{'id':'R7_C2_STRUCTURE_DESTROYING_NULL','status':'READY_FROZEN_8_ONLY'},{'id':'R7_C3_PROBABLE_FUNCTION_ADMISSION','status':'BLOCKED_PENDING_C1_C2'}]);st['roadmap']=road
 st['next_atomic_requirements']=[{'id':'R7_C1_C2_VALIDATION','action':s['next_atomic_requirement']}]+[x for x in st.get('next_atomic_requirements',[]) if x.get('id') not in {'R7_C_POSITIONAL_TEMPLATE_ROLES','R7_C1_C2_VALIDATION'}]
 st['global_claim_ceiling_v2_28']={'cross_validated_internal_context_structure':True,'cross_region_internal_context_structure_transfer':True,'positional_template_candidate_family_established':True,'positional_template_candidate_count':8,'candidate_family_frozen':True,'probable_function_established':False,'exact_word_meaning_established':False,'translation_established':False,'phonetic_value_established':False,'new_anchor_established':False,'decipherment_established':False,'strict_R3B_replication_established':False,'allowed':s['claim_ceiling']['allowed'],'forbidden':s['claim_ceiling']['forbidden']}
 pathlib.Path(a.candidate_out).write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');checks={**pre,'version_v2_28':st['version']=='v2.28','family_frozen':st['global_claim_ceiling_v2_28']['candidate_family_frozen'] is True,'count_8':st['global_claim_ceiling_v2_28']['positional_template_candidate_count']==8,'probable_false':st['global_claim_ceiling_v2_28']['probable_function_established'] is False,'decipherment_false2':st['global_claim_ceiling_v2_28']['decipherment_established'] is False};passed=all(checks.values());audit={'artifact_uuid':'JANUS-LINEAR-A-RESEARCH-STATE-CANONICALITY-AUDIT-2026-08-15-v2.28','version':'v2.28','status':'CANONICALITY_AUDIT_PASS' if passed else 'CANONICALITY_AUDIT_FAIL','executed_at':now,'promotion_spec':a.spec,'parent_state':s['parent_state'],'new_evidence':s['new_evidence'],'parent_sha256':digest(s['parent_state']),'evidence_sha256':digest(s['new_evidence']),'candidate_sha256':digest(a.candidate_out),'checks':checks,'all_checks_pass':passed,'claim_ceiling':s['claim_ceiling']};pathlib.Path(a.audit_out).write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 if not passed:return 2
 st['canonicality']['canonicality_audit_status']='CANONICALITY_AUDIT_PASS';pathlib.Path(a.canonical_out).write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'status':'CANONICAL_V2_28_READY','frozen_candidates':8,'probable_function_established':False},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
