from __future__ import annotations
import argparse, copy, hashlib, json
from pathlib import Path
from datetime import datetime, timezone, timedelta
TZ=timezone(timedelta(hours=3))
def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def digest(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--spec',required=True); ap.add_argument('--candidate-out',required=True); ap.add_argument('--canonical-out',required=True); ap.add_argument('--audit-out',required=True); a=ap.parse_args()
    s=load(a.spec); p=load(s['parent_state']); g=load(s['new_evidence']['G0_result']); cert=load(s['new_evidence']['G0_negative_certificate']); r=s['required']
    pg=p.get('global_claim_ceiling_v2_31',{})
    checks={
      'parent_v2_31':p.get('version')=='v2.31' and p.get('status')=='CURRENT_CANONICAL_RESEARCH_STATE',
      'parent_audit':p.get('canonicality',{}).get('canonicality_audit_status')=='CANONICALITY_AUDIT_PASS',
      'parent_probable':pg.get('probable_region_scoped_structural_function_established') is True,
      'parent_ku_ro':pg.get('admitted_source_word')=='KU-RO','parent_row_opening':pg.get('admitted_probable_structural_function')=='ROW-OPENING-LIKE','parent_f1':pg.get('internal_post_F0_terminal_numeric_slot_refinement_established') is True,
      'g0_status':g.get('status')==r['G0_status'],'support_false':g.get('support',{}).get('support_pass') is r['support_pass'],
      'g0_target_8':g.get('support',{}).get('exchangeable_target_events')==r['observed_exchangeable_target_events'],'g0_controls':g.get('support',{}).get('exchangeable_control_events')==r['exchangeable_control_events'],'g0_objects':g.get('support',{}).get('exchangeable_target_physical_objects')==r['exchangeable_target_objects'],
      'energy':g.get('primary_test',{}).get('observed_energy_distance')==r['energy_distance'],'null_mean':g.get('primary_test',{}).get('null_mean_energy_distance')==r['null_mean_energy'],'p_exact':g.get('primary_test',{}).get('empirical_p')==r['empirical_p'],'loo':g.get('primary_test',{}).get('leave_one_target_object_out_retention_fraction')==r['LOO_retention'],
      'target_median':g.get('postscore_descriptive_profile',{}).get('target_exact_median')==r['target_median'],'control_median':g.get('postscore_descriptive_profile',{}).get('control_exact_median')==r['control_median'],
      'not_established':g.get('admission',{}).get('numeric_payload_distribution_difference_established') is r['numeric_payload_difference_established'],
      'cert_status':cert.get('status')=='G0_SUPPORT_GATE_BLOCKED_8_LT_10_DESPITE_STRONG_INTERNAL_SIGNAL','cert_no_retune':cert.get('anti_retuning',{}).get('support_threshold_lowered_after_result_visibility') is False,
      'total_false':g.get('epistemic_gate',{}).get('TOTAL_or_SUMMARY_semantic_function_established') is False,'meaning_false':g.get('epistemic_gate',{}).get('exact_word_meaning_established') is False,'translation_false':g.get('epistemic_gate',{}).get('translation_established') is False,'decipherment_false':g.get('epistemic_gate',{}).get('decipherment_established') is False
    }
    if not all(checks.values()): raise SystemExit(json.dumps(checks,sort_keys=True))
    now=datetime.now(TZ).isoformat(); st=copy.deepcopy(p); st.update({'artifact_uuid':'JANUS-LINEAR-A-RESEARCH-STATE-2026-08-16-v2.32','timestamp':now,'version':'v2.32','title':'JANUS Linear A canonical state after support-blocked KU-RO terminal numeric payload audit','status':'CURRENT_CANONICAL_RESEARCH_STATE'})
    st['canonicality']={'current_source_of_truth':True,'parent_state':s['parent_state'],'promotion_spec':a.spec,'promotion_prerequisites_pass':True,'history_is_not_deleted':True,'candidate_path':a.candidate_out,'canonicality_audit':a.audit_out,'canonicality_audit_status':'PENDING_UNTIL_AUDIT_EMITTED','promotion_rule_satisfied':True}
    st['R7_G0_terminal_numeric_payload']={'path':s['new_evidence']['G0_result'],'evidence_sha256':digest(s['new_evidence']['G0_result']),'negative_certificate':s['new_evidence']['G0_negative_certificate'],'negative_certificate_sha256':digest(s['new_evidence']['G0_negative_certificate']),'status':g['status'],'support_pass':False,'support_floor_required':10,'exchangeable_target_events':8,'exchangeable_control_events':22,'exchangeable_target_objects':8,'observed_energy_distance':g['primary_test']['observed_energy_distance'],'null_mean_energy_distance':g['primary_test']['null_mean_energy_distance'],'empirical_p':g['primary_test']['empirical_p'],'LOO_retention_fraction':g['primary_test']['leave_one_target_object_out_retention_fraction'],'target_exact_median':g['postscore_descriptive_profile']['target_exact_median'],'control_exact_median':g['postscore_descriptive_profile']['control_exact_median'],'numeric_payload_distribution_difference_established':False,'interpretation':'SUPPORT_BLOCKED_STRONG_INTERNAL_SIGNAL_NOT_ADMITTED'}
    road=[x for x in st.get('roadmap',[]) if x.get('id') not in {'R7_G0_TERMINAL_NUMERIC_PAYLOAD_PROFILE','R7_EXTERNAL_NUMERIC_PAYLOAD_HYPOTHESIS_FREEZE'}]; road.extend([{'id':'R7_G0_TERMINAL_NUMERIC_PAYLOAD_PROFILE','status':'DONE_SUPPORT_BLOCKED_8_LT_10_STRONG_SIGNAL_PRESERVED'},{'id':'R7_EXTERNAL_NUMERIC_PAYLOAD_HYPOTHESIS_FREEZE','status':'READY_BEFORE_EXTERNAL_CONTENT_INSPECTION'}]); st['roadmap']=road
    ids={x['id'] for x in s['next_atomic_requirements']}; st['next_atomic_requirements']=s['next_atomic_requirements']+[x for x in st.get('next_atomic_requirements',[]) if x.get('id') not in ids]
    st['global_claim_ceiling_v2_32']={'probable_region_scoped_structural_function_established':True,'admitted_source_word':'KU-RO','admitted_probable_structural_function':'ROW-OPENING-LIKE','scope_region':'HT','internal_post_F0_terminal_numeric_slot_refinement_established':True,'internal_refinement_label':'ROW-OPENING-WITH-TERMINAL-NUMERIC-SLOT-LIKE','numeric_payload_distribution_difference_established':False,'G0_support_blocked_strong_signal_preserved':True,'G0_exchangeable_target_events':8,'G0_required_exchangeable_target_events':10,'TOTAL_or_SUMMARY_semantic_function_established':False,'universal_cross_region_function_established':False,'exact_word_meaning_established':False,'translation_established':False,'phonetic_value_established':False,'language_family_established':False,'new_anchor_established':False,'decipherment_established':False,'strict_R3B_replication_established':False,'allowed':s['claim_ceiling']['allowed'],'forbidden':s['claim_ceiling']['forbidden']}
    Path(a.candidate_out).write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    audit_checks={**checks,'version_v2_32':st['version']=='v2.32','probable_retained':st['global_claim_ceiling_v2_32']['probable_region_scoped_structural_function_established'] is True,'f1_retained':st['global_claim_ceiling_v2_32']['internal_post_F0_terminal_numeric_slot_refinement_established'] is True,'g0_not_admitted':st['global_claim_ceiling_v2_32']['numeric_payload_distribution_difference_established'] is False,'signal_preserved':st['global_claim_ceiling_v2_32']['G0_support_blocked_strong_signal_preserved'] is True,'total_false2':st['global_claim_ceiling_v2_32']['TOTAL_or_SUMMARY_semantic_function_established'] is False,'decipherment_false2':st['global_claim_ceiling_v2_32']['decipherment_established'] is False}
    passed=all(audit_checks.values()); audit={'artifact_uuid':'JANUS-LINEAR-A-RESEARCH-STATE-CANONICALITY-AUDIT-2026-08-16-v2.32','version':'v2.32','status':'CANONICALITY_AUDIT_PASS' if passed else 'CANONICALITY_AUDIT_FAIL','executed_at':now,'parent_sha256':digest(s['parent_state']),'G0_sha256':digest(s['new_evidence']['G0_result']),'G0_certificate_sha256':digest(s['new_evidence']['G0_negative_certificate']),'candidate_sha256':digest(a.candidate_out),'checks':audit_checks,'all_checks_pass':passed,'claim_ceiling':s['claim_ceiling']}; Path(a.audit_out).write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    if not passed: return 2
    st['canonicality']['canonicality_audit_status']='CANONICALITY_AUDIT_PASS'; Path(a.canonical_out).write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(json.dumps({'status':'CANONICAL_V2_32_READY','KU_RO_probable_function':'ROW-OPENING-LIKE','F1_refinement_retained':True,'G0_numeric_payload_admitted':False,'G0_support':'8/10','decipherment':False},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
