#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--spec',required=True);ap.add_argument('--parent-canonical',required=True);ap.add_argument('--c0',required=True);ap.add_argument('--c1',required=True);ap.add_argument('--c2',required=True);ap.add_argument('--d0',required=True);ap.add_argument('--out',required=True);a=ap.parse_args()
 spec=json.load(open(a.spec,encoding='utf-8'));parent=json.load(open(a.parent_canonical,encoding='utf-8'));c0=json.load(open(a.c0,encoding='utf-8'));c1=json.load(open(a.c1,encoding='utf-8'));c2=json.load(open(a.c2,encoding='utf-8'));d0=json.load(open(a.d0,encoding='utf-8'))
 assert parent['version']=='v2.29' and parent['status']=='CURRENT_CANONICAL_RESEARCH_STATE';assert c0['admitted_candidate_count']==8 and c2['survivor_count']==8 and d0['frozen_candidate_count']==8;assert c1['frozen_candidate_count']==8 and c1['survivor_count']==0
 c0map={(x['role'],x['word_token']):x for x in c0['admitted_candidates']};c2map={(x['role'],x['word_token']):x for x in c2['survivors']};c1map={(x['role'],x['word_token']):x for x in c1['candidate_results']}
 admitted=[];audit=[]
 for x in d0['candidate_results']:
  key=(x['role'],x['word_token']);checks={'in_C0':key in c0map and c0map[key]['POSITIONAL_TEMPLATE_CANDIDATE_ADMITTED'] is True,'in_C2':key in c2map and c2map[key]['C2_STRUCTURE_DEPENDENCE_PASS'] is True,'D0_object':x['D0_OBJECT_BLOCK_PASS'] is True,'D0_status':x['STATUS_ROBUSTNESS_PASS'] is True,'D0_floor':x['C3_SUPPORT_FLOOR_PASS'] is True,'occ_floor':x['dominant_region_occurrences']>=spec['required_chain']['minimum_occurrences'],'object_floor':x['dominant_region_physical_object_count']>=spec['required_chain']['minimum_physical_objects']}
  passes=all(checks.values());row={'role':x['role'],'word_token':x['word_token'],'source_word':x['source_word_after_scoring'],'dominant_region':x['dominant_region'],'checks':checks,'C3_ADMISSION_PASS':passes};audit.append(row)
  if passes:
   flabel=spec['role_to_function_label'][x['role']];c1r=c1map.get(key,{});claim=spec['admitted_claim_template'].format(region=x['dominant_region'],word=x['source_word_after_scoring'],function_label=flabel)
   admitted.append({'word_token':x['word_token'],'source_word':x['source_word_after_scoring'],'source_role':x['role'],'probable_structural_function_label':flabel,'scope_region':x['dominant_region'],'scope':'DOMINANT_REGION_ONLY','C0_heldout_match_rate':c0map[key]['heldout_match_rate'],'C0_BH_q':c0map[key]['BH_q'],'C2_observed_match_rate':c2map[key]['observed_match_rate'],'C2_null_mean_match_rate':c2map[key]['null_mean_match_rate'],'C2_BH_q':c2map[key]['BH_q'],'D0_occurrences':x['dominant_region_occurrences'],'D0_matches':x['dominant_region_matches'],'D0_match_rate':x['dominant_region_match_rate'],'D0_documents':x['dominant_region_document_count'],'D0_physical_objects':x['dominant_region_physical_object_count'],'D0_null_mean_match_rate':x['null_mean_match_rate'],'D0_BH_q':x['BH_q'],'D0_status_strata':x['status_strata'],'C1_universal_cross_region_survival':bool(c1r.get('C1_NESTED_REGION_SURVIVAL',False)),'cross_region_generalization_established':False,'probable_structural_function_admitted':True,'exact_word_meaning_established':False,'translation_established':False,'claim':claim})
 status='REGION_SCOPED_PROBABLE_STRUCTURAL_FUNCTION_ADMITTED' if admitted else 'REGION_SCOPED_PROBABLE_STRUCTURAL_FUNCTION_NOT_ADMITTED'
 out={'artifact_uuid':'JANUS-LINEAR-A-R7-C3-REGION-SCOPED-PROBABLE-FUNCTION-ADMISSION-RESULT-2026-08-15-v0.1','version':'v0.1','status':status,'admission_scope':spec['admission_scope'],'frozen_candidate_count':8,'candidate_family_changed':False,'admission_audit':audit,'admitted_candidate_count':len(admitted),'admitted_candidates':admitted,'epistemic_gate':{'probable_region_scoped_structural_function_established':bool(admitted),'universal_cross_region_function_established':False,'exact_word_meaning_established':False,'translation_established':False,'phonetic_value_established':False,'language_family_established':False,'new_anchor_established':False,'decipherment_established':False,'R3B_external_replication_established':False},'claim_ceiling':spec['claim_ceiling']}
 Path(a.out).write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'status':status,'admitted':len(admitted),'words':[x['source_word'] for x in admitted]},ensure_ascii=False,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
