from __future__ import annotations
import argparse,copy,hashlib,json,pathlib
from datetime import datetime,timezone,timedelta
TZ=timezone(timedelta(hours=3))
def load(p):return json.loads(pathlib.Path(p).read_text(encoding='utf-8'))
def digest(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--spec',required=True);ap.add_argument('--candidate-out',required=True);ap.add_argument('--canonical-out',required=True);ap.add_argument('--audit-out',required=True);a=ap.parse_args();s=load(a.spec);parent=load(s['parent_state']);c1=load(s['C1_evidence']);c2=load(s['C2_evidence']);req=s['required'];ku=[x for x in c2['survivors'] if x.get('source_word_after_scoring')=='KU-RO' and x.get('role')==req['KU_RO_C2_role']]
 pre={'parent_v2_28':parent.get('version')=='v2.28' and parent.get('status')=='CURRENT_CANONICAL_RESEARCH_STATE','c1_count':c1.get('frozen_candidate_count')==req['C1_frozen_candidate_count'],'c1_zero':c1.get('survivor_count')==req['C1_survivor_count'],'c1_family_same':c1.get('candidate_family_changed') is False,'c2_count':c2.get('frozen_candidate_count')==req['C2_frozen_candidate_count'],'c2_eight':c2.get('survivor_count')==req['C2_survivor_count'],'c2_family_same':c2.get('candidate_family_changed') is False,'ku_one':len(ku)==1,'ku_rate':len(ku)==1 and ku[0]['observed_match_rate']==req['KU_RO_C2_observed_match_rate'],'ku_q':len(ku)==1 and ku[0]['BH_q']==req['KU_RO_C2_BH_q'],'c1_probable_false':c1['epistemic_gate']['probable_function_established'] is False,'c2_probable_false':c2['epistemic_gate']['probable_function_established'] is False,'decipherment_false':c1['epistemic_gate']['decipherment_established'] is False and c2['epistemic_gate']['decipherment_established'] is False}
 if not all(pre.values()):raise SystemExit(json.dumps(pre,sort_keys=True))
 st=copy.deepcopy(parent);now=datetime.now(TZ).isoformat();st.update({'artifact_uuid':'JANUS-LINEAR-A-RESEARCH-STATE-2026-08-15-v2.29','timestamp':now,'version':'v2.29','title':'JANUS Linear A canonical state after frozen candidate region/adversarial validation','status':'CURRENT_CANONICAL_RESEARCH_STATE'});st['canonicality']={'current_source_of_truth':True,'parent_state':s['parent_state'],'promotion_spec':a.spec,'promotion_prerequisites_pass':True,'history_is_not_deleted':True,'candidate_path':a.candidate_out,'canonicality_audit':a.audit_out,'canonicality_audit_status':'PENDING_UNTIL_AUDIT_EMITTED','promotion_rule_satisfied':True}
 lane=st.setdefault('R7_formula_role_lane',{});lane['R7_C1']={'path':s['C1_evidence'],'status':c1['status'],'evidence_sha256':digest(s['C1_evidence']),'frozen_candidate_count':8,'survivor_count':0,'interpretation':'Universal nested cross-region survival not established; lack of sufficient non-dominant-region support is explicitly distinct from functional contradiction.'};lane['R7_C2']={'path':s['C2_evidence'],'status':c2['status'],'evidence_sha256':digest(s['C2_evidence']),'frozen_candidate_count':8,'survivor_count':8,'KU_RO':ku[0]};lane['status']='C0_8_FROZEN_C1_UNIVERSAL_NOT_ESTABLISHED_C2_8_STRUCTURE_DEPENDENT_REGION_SCOPED_VALIDATION_READY'
 road=[x for x in st.get('roadmap',[]) if x.get('id') not in {'R7_C1_COMPLETE_REGION_HOLDOUT','R7_C2_STRUCTURE_DESTROYING_NULL','R7_D0_REGION_SCOPED_OBJECT_STATUS_VALIDATION','R7_C3_PROBABLE_FUNCTION_ADMISSION'}];road.extend([{'id':'R7_C1_COMPLETE_REGION_HOLDOUT','status':'DONE_NO_TWO_REGION_SURVIVORS_SUPPORT_LIMITED'},{'id':'R7_C2_STRUCTURE_DESTROYING_NULL','status':'DONE_8_OF_8_SURVIVE'},{'id':'R7_D0_REGION_SCOPED_OBJECT_STATUS_VALIDATION','status':'READY_FROZEN_8_ONLY'},{'id':'R7_C3_PROBABLE_FUNCTION_ADMISSION','status':'UNIVERSAL_BLOCKED_REGION_SCOPED_PENDING_D0'}]);st['roadmap']=road
 st['next_atomic_requirements']=[{'id':'R7_D0_REGION_SCOPED_OBJECT_STATUS_VALIDATION','action':s['next_atomic_requirement']}]+[x for x in st.get('next_atomic_requirements',[]) if x.get('id') not in {'R7_C1_C2_VALIDATION','R7_D0_REGION_SCOPED_OBJECT_STATUS_VALIDATION'}]
 st['global_claim_ceiling_v2_29']={'positional_template_candidate_count':8,'C2_structure_dependent_candidate_count':8,'universal_cross_region_survivor_count':0,'universal_probable_function_established':False,'region_scoped_probable_function_established':False,'exact_word_meaning_established':False,'translation_established':False,'phonetic_value_established':False,'new_anchor_established':False,'decipherment_established':False,'strict_R3B_replication_established':False,'allowed':s['claim_ceiling']['allowed'],'forbidden':s['claim_ceiling']['forbidden']}
 pathlib.Path(a.candidate_out).write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');checks={**pre,'version_v2_29':st['version']=='v2.29','universal_false':st['global_claim_ceiling_v2_29']['universal_probable_function_established'] is False,'regional_false':st['global_claim_ceiling_v2_29']['region_scoped_probable_function_established'] is False,'decipherment_false2':st['global_claim_ceiling_v2_29']['decipherment_established'] is False};passed=all(checks.values());audit={'artifact_uuid':'JANUS-LINEAR-A-RESEARCH-STATE-CANONICALITY-AUDIT-2026-08-15-v2.29','version':'v2.29','status':'CANONICALITY_AUDIT_PASS' if passed else 'CANONICALITY_AUDIT_FAIL','executed_at':now,'promotion_spec':a.spec,'parent_state':s['parent_state'],'C1_evidence':s['C1_evidence'],'C2_evidence':s['C2_evidence'],'parent_sha256':digest(s['parent_state']),'C1_sha256':digest(s['C1_evidence']),'C2_sha256':digest(s['C2_evidence']),'candidate_sha256':digest(a.candidate_out),'checks':checks,'all_checks_pass':passed,'claim_ceiling':s['claim_ceiling']};pathlib.Path(a.audit_out).write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 if not passed:return 2
 st['canonicality']['canonicality_audit_status']='CANONICALITY_AUDIT_PASS';pathlib.Path(a.canonical_out).write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'status':'CANONICAL_V2_29_READY','C2_survivors':8,'universal_C1_survivors':0,'region_scoped_validation_ready':True},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
