from __future__ import annotations
import argparse, copy, hashlib, json, pathlib
from datetime import datetime, timezone, timedelta
TZ=timezone(timedelta(hours=3))
def load(p): return json.loads(pathlib.Path(p).read_text(encoding='utf-8'))
def digest(p): return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--spec',required=True);ap.add_argument('--candidate-out',required=True);ap.add_argument('--canonical-out',required=True);ap.add_argument('--audit-out',required=True);a=ap.parse_args()
    s=load(a.spec);parent=load(s['parent_state']);ev=load(s['new_evidence']);ni=[x for x in ev['candidate_results'] if x.get('source_word_after_scoring')=='NI' and x.get('role')=='RIGHT_NUMERIC']
    pre={'parent_v2_22':parent.get('version')=='v2.22' and parent.get('status')=='CURRENT_CANONICAL_RESEARCH_STATE','status_exact':ev.get('status')==s['required_status'],'family_2':ev.get('candidate_family_size')==2,'survivors_0':ev.get('survivor_count')==0,'no_blind_credit':ev['leakage_and_credit'].get('blind_confirmation_credit') is False,'no_independent_confirmation':ev['leakage_and_credit'].get('independent_confirmation_claimed') is False,'ni_one':len(ni)==1,'ni_not_survive':len(ni)==1 and ni[0].get('REGION_CONDITIONED_SURVIVAL') is False,'ni_p_exact':len(ni)==1 and ni[0].get('region_conditioned_p')==s['required']['NI_RIGHT_region_conditioned_p'],'ni_q_exact':len(ni)==1 and ni[0].get('region_conditioned_BH_q')==s['required']['NI_RIGHT_region_conditioned_BH_q'],'meaning_false':ev['epistemic_gate'].get('meaning_established') is False,'decipherment_false':ev['epistemic_gate'].get('decipherment_established') is False}
    if not all(pre.values()):raise SystemExit(json.dumps(pre,sort_keys=True))
    st=copy.deepcopy(parent);now=datetime.now(TZ).isoformat();st.update({'artifact_uuid':'JANUS-LINEAR-A-RESEARCH-STATE-2026-08-14-v2.23','timestamp':now,'version':'v2.23','title':'JANUS Linear A canonical state after KH-conditioned NI confound audit','status':'CURRENT_CANONICAL_RESEARCH_STATE'})
    st['canonicality']={'current_source_of_truth':True,'parent_state':s['parent_state'],'promotion_spec':a.spec,'promotion_prerequisites_pass':True,'history_is_not_deleted':True,'candidate_path':a.candidate_out,'canonicality_audit':a.audit_out,'canonicality_audit_status':'PENDING_UNTIL_AUDIT_EMITTED','promotion_rule_satisfied':True}
    st['R6_numeric_adjacency_role_lane']['R6_1']={'path':s['new_evidence'],'status':ev['status'],'evidence_sha256':digest(s['new_evidence']),'candidate_family_size':2,'survivor_count':0,'NI_RIGHT_NUMERIC_region_conditioned':{'heldout_rate':ni[0]['heldout_adjacency_rate'],'region_background_rate':ni[0]['region_background_adjacency_rate'],'p_value':ni[0]['region_conditioned_p'],'BH_q':ni[0]['region_conditioned_BH_q'],'survives':False},'credit':'POSTHOC_CORRECTIVE_NO_BLIND_CONFIRMATION'}
    st['R6_numeric_adjacency_role_lane']['status']='R6_0_NO_FDR_ADMISSION_R6_1_REGION_CONDITIONED_NOT_ROBUST'
    road=[x for x in st.get('roadmap',[]) if x.get('id')!='R6_1_REGION_CONDITIONED_NULL_AUDIT'];road.append({'id':'R6_1_REGION_CONDITIONED_NULL_AUDIT','status':'DONE_POSTHOC_NEGATIVE_0_SURVIVORS'});st['roadmap']=road
    st['next_atomic_requirements']=[{'id':'INTERNAL_DISCOVERY_NEXT','action':s['next_atomic_requirement']}]+[x for x in st.get('next_atomic_requirements',[]) if x.get('id')!='R6_1_REGION_CONDITIONED_NULL_AUDIT']
    st['global_claim_ceiling_v2_23']={'sign_level_context_structure_learned_cross_validated':True,'NI_right_numeric_pattern_admitted':False,'NI_region_conditioned_survival':False,'NI_meaning_established':False,'translation_established':False,'phonetic_value_established':False,'new_anchor_established':False,'decipherment_established':False,'strict_R3B_replication_established':False,'allowed':s['claim_ceiling']['allowed'],'forbidden':s['claim_ceiling']['forbidden']}
    pathlib.Path(a.candidate_out).write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    checks={**pre,'version_v2_23':st['version']=='v2.23','ni_not_admitted':st['global_claim_ceiling_v2_23']['NI_right_numeric_pattern_admitted'] is False,'ni_meaning_false':st['global_claim_ceiling_v2_23']['NI_meaning_established'] is False,'decipherment_false2':st['global_claim_ceiling_v2_23']['decipherment_established'] is False};passed=all(checks.values());audit={'artifact_uuid':'JANUS-LINEAR-A-RESEARCH-STATE-CANONICALITY-AUDIT-2026-08-14-v2.23','version':'v2.23','status':'CANONICALITY_AUDIT_PASS' if passed else 'CANONICALITY_AUDIT_FAIL','executed_at':now,'promotion_spec':a.spec,'parent_state':s['parent_state'],'new_evidence':s['new_evidence'],'parent_sha256':digest(s['parent_state']),'evidence_sha256':digest(s['new_evidence']),'candidate_sha256':digest(a.candidate_out),'checks':checks,'all_checks_pass':passed,'claim_ceiling':s['claim_ceiling']};pathlib.Path(a.audit_out).write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    if not passed:return 2
    st['canonicality']['canonicality_audit_status']='CANONICALITY_AUDIT_PASS';pathlib.Path(a.canonical_out).write_text(json.dumps(st,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'status':'CANONICAL_V2_23_READY','NI_region_survival':False,'decipherment_established':False},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
